#!/bin/bash

usage() {
    echo "Uso: $0 [-i] archivo"
    echo "  Sin flags: agrega chattr +i al archivo en /opt/4rji/bin"
    echo "  -i       : quita chattr -i al archivo en /opt/4rji/bin"
    exit 1
}

remove=false

while getopts ":i" opt; do
    case $opt in
        i) remove=true ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))

[ $# -eq 0 ] && usage

archivo="/opt/4rji/bin/$1"

if [ ! -e "$archivo" ]; then
    echo "El archivo o directorio '$archivo' no existe."
    exit 1
fi

if $remove; then
    sudo chattr -i "$archivo"
else
    sudo chattr +i "$archivo"
fi
