#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Proporcione un archivo."
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Archivo no existe: $1"
    exit 1
fi

chmod +x "$1"
echo "Permisos +x asignados: $1"
