#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Proporcione un archivo."
    exit 1
fi

archivo="$1"

if [ ! -f "$archivo" ]; then
    echo "Archivo no existe: $archivo"
    exit 2
fi

chmod +x "$archivo"
exec "./$archivo"
