#!/usr/bin/env bash

# Función para crear un directorio temporal en /dev/shm
function mktem() {
    if [ -n "$1" ]; then
        new_dir=$(mktemp -d /dev/shm/tmp."$1".XXXXXX)
    else
        new_dir=$(mktemp -d /dev/shm/tmp.XXXXXX)
    fi
    echo "Directorio creado en: $new_dir"
    cd "$new_dir" || return
    echo "Cambiado al directorio: $PWD"
}

# Crear el directorio de destino si no existe
mkdir -p /opt/4rji/

# Usar la función mktem para crear un directorio temporal
mktem "download"

# Descargar la base de datos desde el commit indicado
curl --fail --location \
    --output GeoLite2-City.mmdb.gz \
    https://raw.githubusercontent.com/wp-statistics/GeoLite2-City/a1a4edef893a465c59eea87fc13ee812b04b8536/GeoLite2-City.mmdb.gz

# Descomprimir la base de datos en el directorio de destino
gzip --decompress GeoLite2-City.mmdb.gz
sudo mv GeoLite2-City.mmdb /opt/4rji/



echo "Descarga y extracción completada en /opt/4rji/"
