#!/usr/bin/env bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
RESET='\033[0m'

function ctrl_c {
    echo -e "\n\n${RED}[!] Exiting...${RESET}\n"
    tput cnorm
    exit 1
}

trap ctrl_c SIGINT

function checkPort {
    (exec 3<> /dev/tcp/$1/$2) 2>/dev/null
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}[+]${RESET} Host ${CYAN}$1${RESET} - Port ${YELLOW}$2${RESET} ${GREEN}(OPEN)${RESET}"
    fi
    exec 3<&-
    exec 3>&-
}

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo -e "\n${RED}[!] Usage: $0 <ip> <start-port> <end-port>${RESET}"
    echo -e "    ${YELLOW}Example: $0 192.168.1.1 22 80${RESET}\n"
    exit 1
fi

ports=( $(seq $2 $3) )

tput civis

for port in ${ports[@]}; do
    checkPort $1 $port
done

wait
tput cnorm
