#!/usr/bin/env bash
echo ""
if [[ -z "$1" ]]; then
  echo -e "\033[91mPor favor, proporcione el nombre del archivo como argumento.\033[0m"
  exit 1
fi

filename="$1"
filepath=$(readlink -f "$filename")

echo -e "\033[33mFile path:\033[0m"
echo -e "\033[34m$filepath\033[0m"

if command -v pbcopy &>/dev/null; then
  printf '%s' "$filepath" | pbcopy
  echo -e "\033[92mFile path '$filename' se ha copiado en el portapapeles.\033[0m"
elif command -v xclip &>/dev/null; then
  printf '%s' "$filepath" | xclip -selection clipboard
  echo ""
  echo -e "\033[92mLa siguiente ruta '$filename' ha sido copiada en el portapapeles.\033[0m"
else
  echo -e "\033[91mNo se pudo encontrar el comando necesario para copiar al portapapeles.\033[0m"
  exit 1
fi

echo -e "\033[34m$filepath\033[0m"
echo ""
