#!/usr/bin/env bash

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
BLUE='\033[1;34m'
RESET='\033[0m'
SEP="${CYAN}_________________________________________________________${RESET}"

echo ""

if [ -z "$1" ]; then
  echo -e "${RED}[!] Usage: $0 <wireguard_interface>${RESET}"
  exit 1
fi

INTERFACE=$1
CONFIG_FILE="/etc/wireguard/$INTERFACE.conf"


if ! systemctl is-active --quiet systemd-resolved; then
  echo -e "${YELLOW}[?] systemd-resolved is not active. Activate it? (y/n)${RESET}"
  read -n1 activate_resolved
  echo ""
  if [ "$activate_resolved" = "y" ]; then
    sudo systemctl start systemd-resolved
  fi
fi

if ! command -v nano &> /dev/null; then
  echo -e "${RED}[!] Nano not installed.${RESET}"
  exit 1
fi

show_menu() {
  echo -e "\n${SEP}\n"
  echo -e "  ${BLUE}Interface:${RESET} ${CYAN}$INTERFACE${RESET}\n"
  echo -e "  ${GREEN}c)${RESET} Connect"
  echo -e "  ${YELLOW}d)${RESET} Disconnect"
  echo -e "  ${RED}s)${RESET} Status"
  echo -e "  ${CYAN}m)${RESET} Modify config"
  echo -e "  ${CYAN}q)${RESET} Exit"
  echo -e "\n${SEP}\n"
}

while true; do
  show_menu
  echo -ne "${BLUE}Option [c/d/s/m/q]: ${RESET}"
  read -n1 choice
  echo ""

  case $choice in
    c)
      echo -e "${GREEN}\n[+] Connecting $INTERFACE...${RESET}"
      sudo wg-quick up $INTERFACE
      ;;
    d)
      echo -e "${YELLOW}\n[-] Disconnecting $INTERFACE...${RESET}"
      sudo wg-quick down $INTERFACE
      ;;
    s)
      echo -e "${CYAN}\n[*] Status: $INTERFACE${RESET}"
      sudo wg show $INTERFACE
      ;;
    m)
      echo -e "${CYAN}\n[*] Opening config: $CONFIG_FILE${RESET}"
      sudo nano $CONFIG_FILE
      ;;
    q)
      echo -e "${CYAN}\nBye.${RESET}"
      exit 0
      ;;
    *)
      echo -e "${RED}\n[!] Invalid option [c/d/s/m/q]${RESET}"
      ;;
  esac
done
