#!/usr/bin/env bash

echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"

onlineFile=$(mktemp)
offlineFile=$(mktemp)

# Colores
BLUE="\033[34m"
WHITE="\033[37m"
GREEN="\033[32m"
RED="\033[31m"
RESET="\033[0m"

aliases=()
hostnames=()
ports=()
current_indices=()

while read -r line; do
    line=$(echo "$line" | sed 's/#.*//;s/^\s*//;s/\s*$//')
    [[ -z "$line" ]] && continue

    key=$(echo "$line" | awk '{print tolower($1)}')
    value=$(echo "$line" | awk '{print $2}')

    if [[ "$key" == "host" ]]; then
        IFS=' ' read -r -a host_array <<< "$value"
        current_indices=()
        for host in "${host_array[@]}"; do
            aliases+=("$host")
            hostnames+=("")
            ports+=(22)
            idx=$((${#aliases[@]} - 1))
            current_indices+=("$idx")
        done
    elif [[ "$key" == "hostname" ]]; then
        for idx in "${current_indices[@]}"; do
            hostnames[$idx]="$value"
        done
    elif [[ "$key" == "port" ]]; then
        for idx in "${current_indices[@]}"; do
            ports[$idx]="$value"
        done
    fi
done < ~/.ssh/config

for idx in "${!aliases[@]}"; do
    host="${aliases[$idx]}"
    hostname="${hostnames[$idx]}"
    port="${ports[$idx]}"
    [[ -z "$hostname" ]] && hostname="$host"
    
    {
        if nc -zv -w1 "$hostname" "$port" &>/dev/null; then
            printf "%b - %b (%bonline%b)\n" "${BLUE}${host}${RESET}" "${WHITE}${hostname}:${port}${RESET}" "${GREEN}" "${RESET}" >> "$onlineFile"
        else
            printf "%b - %b (%boffline%b)\n" "${BLUE}${host}${RESET}" "${WHITE}${hostname}:${port}${RESET}" "${RED}" "${RESET}" >> "$offlineFile"
        fi
    } &
done

wait

echo "Offline:"
sort "$offlineFile"


echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"
echo "Online:"
sort "$onlineFile"

rm "$onlineFile" "$offlineFile"

echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"